Repository datavisyn/github-workflows, pull requests merged in 2023-11, with the labels that each got.

#29 feat: Add playwright option next to cypress option
  .github/workflows/build-node-python.yml
Labels: release: patch

#33 deps: update to cypress github action v6 and Node 20
  .github/workflows/build-node-python.yml
  .github/workflows/build-node.yml
  .github/workflows/build-product.yml
  .github/workflows/build-push-docker.yml
  .github/workflows/build-push-helm-chart.yml
  .github/workflows/build-python.yml
  .github/workflows/build-single-product-part.yml
  .github/workflows/build-workspace-product-part.yml
  .github/workflows/check-helm-chart-version.yml
  .github/workflows/deploy-product.yml
  .github/workflows/publish-node-python.yml
  .github/workflows/publish-node.yml
  .github/workflows/publish-python.yml
  .github/workflows/release-product.yml
  .github/workflows/release-source.yml
Labels: release: minor, dependencies

#35 Migrate some secrets to vars
  .github/actions/lint-github-actions/action.yml
  .github/workflows/build-product.yml
  .github/workflows/build-push-docker.yml
  .github/workflows/build-push-helm-chart.yml
  .github/workflows/build-single-product-part.yml
  .github/workflows/build-workspace-product-part.yml
  .github/workflows/deploy-product.yml
  .github/workflows/lint.yml
  .github/workflows/publish-node-python.yml
  .github/workflows/publish-node.yml
  .github/workflows/publish-python.yml
  .github/workflows/release-product.yml
  .github/workflows/release-source.yml
Labels: type: refactor
